name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t react-test -f Dockerfile.dev .

    - name: Run Tests
      run: docker run -e CI=true react-test npm run test
